// The theme as files (spec 043): the local `jump theme check` and the
// browser code editor run the same checks as the server, and both hand out
// the same schema of everything the server accepts.

import { CATALOG, validateContent } from './content.js';
import { DOCUMENTS, validateDocument } from './documents.js';
import { COLOR_SCHEMES_MAX, CONTENT_MAX_BYTES, DOCUMENT_MAX_BYTES, SECTIONS_PER_DOCUMENT, SETTINGS_MAX_BYTES } from './limits.js';
import { getPreset } from './presets/index.js';
import { BLOCKS, COMMON_SECTION_FIELDS, SECTIONS } from './registry.js';
import { FONTS, SETTINGS_GROUPS, validateSettings } from './settings.js';

/** The server's own checks, run locally (no sanitising: the server does that on save). */
export function checkTheme(local, presetKey) {
  const errors = {};
  const settings = validateSettings(local.settings);
  Object.assign(errors, Object.fromEntries(Object.entries(settings.errors).map(([k, v]) => [`settings.${k}`, v])));
  const content = validateContent(local.content);
  Object.assign(errors, Object.fromEntries(Object.entries(content.errors).map(([k, v]) => [`content.${k}`, v])));
  const schemes = local.settings?.colors?.schemes ?? getPreset(presetKey)?.settings?.colors?.schemes ?? [];
  const schemeIds = new Set(schemes.map((s) => s.id));
  for (const [key, data] of Object.entries(local.documents)) {
    if (!DOCUMENTS[key]) {
      errors[`documents.${key}`] = 'is not a theme document';
      continue;
    }
    const checked = validateDocument(key, data, { schemeIds });
    for (const [path, message] of Object.entries(checked.errors)) errors[`documents.${key}.${path}`] = message;
  }
  return errors;
}

/** Everything the server accepts, for people and AI assistants. */
export function themeSchema() {
  return {
    note: 'Generated by `jump theme pull`. The server validates every push against these definitions.',
    documents: DOCUMENTS,
    sections: SECTIONS,
    blocks: BLOCKS,
    commonSectionFields: COMMON_SECTION_FIELDS,
    settings: SETTINGS_GROUPS,
    fonts: FONTS,
    content: CATALOG,
    limits: { DOCUMENT_MAX_BYTES, SETTINGS_MAX_BYTES, CONTENT_MAX_BYTES, SECTIONS_PER_DOCUMENT, COLOR_SCHEMES_MAX },
  };
}

