import { expect as baseExpect, test, type Page } from '@playwright/test';
import { signInAsStaff } from './helpers/session';
import { mockThemeEditorApi } from './helpers/themeEditorMocks';

// Online Store › Edit code: the theme's JSON files in Monaco against the
// mocked themes API. Monaco is served by the app itself (/api/monaco), so the
// spec needs no network.

const expect = baseExpect.configure({ timeout: 20_000 });
const CODE = '/admin/online-store/themes/theme-main/code';

type Patch = [(string | number)[], unknown];

async function openCode(page: Page) {
  await page.goto(CODE);
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('"content"', { timeout: 60_000 });
}

/** Set values in one open file through Monaco's own model, as typing would. */
async function editFile(page: Page, path: string, patches: Patch[]) {
  await page.evaluate(
    ({ path, patches }) => {
      const monaco = (window as any).monaco;
      const model = monaco.editor.getModels().find((m: any) => m.uri.path.replace(/^\//, '') === path);
      const doc = JSON.parse(model.getValue());
      for (const [at, value] of patches) {
        const parent = at.slice(0, -1).reduce((node: any, key) => node[key], doc);
        parent[at[at.length - 1]] = value;
      }
      model.setValue(JSON.stringify(doc, null, 2) + '\n');
    },
    { path, patches },
  );
}

const markers = (page: Page) => page.evaluate(() => (window as any).monaco.editor.getModelMarkers({ owner: 'jump-theme' }).length);

test.describe('theme code editor', () => {
  test.describe.configure({ timeout: 120_000 });

  test.beforeEach(async ({ page, baseURL }) => {
    await signInAsStaff(page, { id: 'editor-admin', email: 'editor-admin@test.com', role: 'ADMIN' }, baseURL!);
  });

  test('opens the theme as files, full screen, with the schema read only', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await mockThemeEditorApi(page);
    await openCode(page);
    await expect(page.locator('aside nav a', { hasText: 'Online store' })).toHaveCount(0);
    const explorer = page.getByRole('complementary', { name: 'Explorer' });
    for (const name of ['settings.json', 'content.json', 'header.json', 'footer.json', 'home.json', 'events.json', '.jump/schema.json']) {
      await expect(explorer.getByRole('button', { name, exact: true })).toBeVisible();
    }
    await expect(page.getByTestId('breadcrumb')).toHaveText('documents › home.json');
    await explorer.getByRole('button', { name: '.jump/schema.json', exact: true }).click();
    await expect(page.getByTestId('breadcrumb')).toContainText('(read only)');
    await expect(page.locator('.monaco-editor .view-lines')).toContainText('Generated by `jump theme pull`');
    await expect(page.getByTestId('problem-count')).toHaveText('0');
    expect(errors).toEqual([]);
  });

  test('a width edit saves only the changed document, with its version', async ({ page }) => {
    const api = await mockThemeEditorApi(page);
    await openCode(page);
    await editFile(page, 'documents/home.json', [
      [['content', 0, 'props', 'sectionWidth'], 'full'],
      [['root', 'props', 'pageWidth'], 1100],
    ]);
    const tab = page.getByRole('tab', { name: /home\.json/ });
    await expect(tab.getByLabel('Unsaved changes')).toBeVisible();
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: /editing your live store/ })).toBeVisible();
    expect(api.saves).toHaveLength(1);
    expect(Object.keys(api.saves[0])).toEqual(['themeVersion', 'documents']);
    expect(Object.keys(api.saves[0].documents)).toEqual(['home']);
    expect(api.saves[0].documents.home.data.content[0].props.sectionWidth).toBe('full');
    expect(api.saves[0].documents.home.data.root.props.pageWidth).toBe(1100);
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled();
  });

  test('server checks run in the browser: a bad value is marked and nothing is sent', async ({ page }) => {
    const api = await mockThemeEditorApi(page);
    await openCode(page);
    await editFile(page, 'documents/home.json', [[['content', 0, 'props', 'sectionWidth'], 'huge']]);
    await expect(page.getByTestId('problem-count')).toHaveText('1');
    await expect.poll(() => markers(page)).toBe(1);
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('alert').filter({ hasText: 'Fix the problem before saving.' })).toBeVisible();
    await expect(page.getByRole('region', { name: 'Problems' })).toContainText('content.0.props.sectionWidth');
    expect(api.saves).toHaveLength(0);
  });

  test('a 409 explains the conflict and keeps the edits to apply after reloading', async ({ page }) => {
    await mockThemeEditorApi(page, { conflictOnSave: true });
    await openCode(page);
    await editFile(page, 'documents/home.json', [[['content', 0, 'props', 'sectionWidth'], 'narrow']]);
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    const dialog = page.getByRole('alertdialog', { name: 'This theme changed elsewhere' });
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button', { name: 'Reload' }).click();
    await page.getByRole('button', { name: 'Apply them again' }).click();
    await expect(page.locator('.monaco-editor .view-lines')).toContainText('narrow');
  });

  test('reached from the visual editor', async ({ page }) => {
    await mockThemeEditorApi(page);
    await page.goto('/admin/online-store/themes/theme-main/editor');
    await page.getByRole('button', { name: 'More editor actions' }).click();
    await page.getByRole('menuitem', { name: 'Edit code' }).click();
    await expect(page).toHaveURL(/\/themes\/theme-main\/code$/);
  });
});
